spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  data:
    mongodb:
      uri: ${AI_MONGODB_URI:mongodb://mongo:27017/airecommendationfitness}
      database: ${AI_MONGODB_DATABASE:airecommendationfitness}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

gemini:
  api:
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent}
    key: ${GEMINI_API_KEY:}

kafka:
  topic:
    name: ${KAFKA_ACTIVITY_TOPIC:activity-events}
    delete-name: ${KAFKA_ACTIVITY_DELETE_TOPIC:activity-delete-events}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

server:
  port: ${AI_SERVICE_PORT:8083}
