spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: classpath:/config


server:
  port: ${CONFIG_SERVER_PORT:8888}
